language: haxe

# Add encrypted API key
env:
  global:
    - secure: Bzclr4qLWZemArvsSdgBwDBhVmLb4tTg/8dB/1eGQe2hi4UKCVT5+AyAO2yD6/+U5RjlCEMzkEayWpAJj3ZEBtSJDbCPsACRNnfynDgXKdTvC7ulBS8+cSTWdZBupgj1u/PQaBJGkIg9QrZL360qdfdCL1U1HVV2Sezm3KLHNkKHNi09bMwSnM7Gqm6ObrTnmwK2thUsYyWeC8lg8OVaLDPRz4OWTdTV9h2WJO35Bd6ml8dZDEeR/7zooZdyyngEs5TfjSMeA4dPjeu2qdN7C+gg6MkPy5BaEOOAJrh3rHr/ca4kmxPwutPfCA3Bwb0u5C/tHTMJmriKBJJk247XDP2wLvIq7i6rFjt+BUVu0u8MbRnKNqA2sOp4+1dOKHlWurxeMMOyuLSjeEM2hbRZA/LVTH510C27zv14/hGIbukItO9jJLZ230KkNclNuXyRF9bdkvAykYJrufOTBtfUceCO3MzszcdtGXHQugKwWt5XIUYPdZcPH1qe/LzRRs9NwGjF3Kv4YFuBBJPs4NouQqcWLShD1aO/+PlTs2/v9mE8qlk1G0QdUxhD64psUCbLVm0lfnDlTOw40dyNO5FDkJvFbkh1V5/KuPqPwTCa5JqdnHkdGY/8UMVSxZy+N86/af1r+dkodLuKsJk+84mLjvnK+jcAiszKfv1HXYPR3+E=

matrix:
  include:
    - os: linux
      sudo: required
      dist: focal
    - os: osx
      osx_image: xcode12.5
    

# Blacklist
branches:
  only:
    - master

before_install:
  - wget http://nmehost.com/releases/hxcpp/hxcpp-3.4.214.zip
  - haxelib install hxcpp-3.4.214.zip

# Install dependencies
install:
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib list

# Build the haxelib, then build the demo
script:
  # Build for regular targets with no haxelibs set up
  - haxelib run openfl build "Project.xml" flash
  - haxelib run openfl build "Project.xml" html5 -minify -release
  
  # Build the haxelib ndlls for iOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    pushd lib/samcodes-consent/project;
    chmod +x rebuild_ndlls.sh;
    ./rebuild_ndlls.sh;
    popd;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then haxelib run openfl build "Project.xml" ios -simulator ; fi

# Deploy the generated demo using Travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: export/html5/bin
  github_token: $GITHUB_API_KEY
  on:
    branch: master
